name: Android CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v2

      - name: Grant Execute Permission to Gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Run UI tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
            api-level: 31
            target: google_apis
            arch: x86_64
            profile: pixel
            disable-animations: true
            emulator-options: "-no-snapshot-save -no-boot-anim -camera-back none -gpu swiftshader_indirect"
            script: |
              adb wait-for-device
              sleep 30  # give it extra time to be fully ready
              adb shell input keyevent 82
              ./gradlew connectedDebugAndroidTest
      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: app/build/outputs/apk/release/app-release.apk
      - name: Setup Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Set up service account
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > "${{ github.workspace }}/gcloud-key.json"
          export GOOGLE_APPLICATION_CREDENTIALS="${{ github.workspace }}/gcloud-key.json"

      - name: Deploy Firebase Functions
        run: firebase deploy --only functions

  