name: Android CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false

      - name: Grant Execute Permission to Gradlew
        run: chmod +x gradlew

      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

      - name: Assemble Release APK
        run: ./gradlew assembleRelease

      - name: Build APK
        run: |
          ./gradlew assembleRelease
          find app/build/outputs/ -type f

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Install required emulator dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libpulse0 \
            libnss3 \
            libx11-6 \
            libglu1-mesa \
            libxtst6 \
            libxrandr2 \
            libxrender1 \
            libxcursor1 \
            libxi6 \
            libasound2 \
            libdbus-1-3 \
            libfontconfig1 \
            libxcb-cursor0 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxinerama1 \
            libsm6 \
            libatk1.0-0 \
            libxext6 \
            libxft2 \
            libpangocairo-1.0-0 \
            libpango-1.0-0 \
            libgtk-3-0 || true

      - name: Run UI tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        continue-on-error: true
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel
          headless: true
          disable-animations: true
          emulator-options: "-no-window -no-audio -no-boot-anim -camera-back none -gpu swiftshader_indirect -accel off"
          script: ./gradlew connectedDebugAndroidTest

      - name: Upload APK to Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: app/build/outputs/apk/release/app-release.apk

      - name: Setup Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Authenticate with Firebase
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > "${{ github.workspace }}/gcloud-key.json"
          export GOOGLE_APPLICATION_CREDENTIALS="${{ github.workspace }}/gcloud-key.json"
          firebase login:ci --token "$(cat $GOOGLE_APPLICATION_CREDENTIALS)" || true

      - name: Deploy Firebase Functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ github.workspace }}/gcloud-key.json"
        run: firebase deploy --only functions
